
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'\xa9\xe9H\x08\xba\x97\xb2,\xd2]\xad\xdf4\xe3\\g'
    
_lr_action_items = {'TYPE_CHAR':([0,],[2,]),'$end':([3,8,16,],[0,-1,-2,]),'CHAR':([9,],[12,]),'TYPE_DOUBLE':([0,],[1,]),'INT':([9,],[14,]),'FLOAT':([9,],[10,]),'TYPE_INT':([0,],[5,]),'DOUBLE':([9,],[11,]),'TYPE_FLOAT':([0,],[6,]),'SEMICOLON':([7,10,11,12,13,14,15,],[8,-8,-9,-10,-11,-7,16,]),'ID':([1,2,4,5,6,9,],[-6,-5,7,-3,-4,13,]),'ASSIGN':([7,],[9,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'type':([0,],[4,]),'var_decl':([0,],[3,]),'value':([9,],[15,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> var_decl","S'",1,None,None,None),
  ('var_decl -> type ID SEMICOLON','var_decl',3,'p_var_decl','rules.py',51),
  ('var_decl -> type ID ASSIGN value SEMICOLON','var_decl',5,'p_var_decl','rules.py',52),
  ('type -> TYPE_INT','type',1,'p_type','rules.py',62),
  ('type -> TYPE_FLOAT','type',1,'p_type','rules.py',63),
  ('type -> TYPE_CHAR','type',1,'p_type','rules.py',64),
  ('type -> TYPE_DOUBLE','type',1,'p_type','rules.py',65),
  ('value -> INT','value',1,'p_value','rules.py',70),
  ('value -> FLOAT','value',1,'p_value','rules.py',71),
  ('value -> DOUBLE','value',1,'p_value','rules.py',72),
  ('value -> CHAR','value',1,'p_value','rules.py',73),
  ('value -> ID','value',1,'p_value','rules.py',74),
]
